# Config for AI instruction docs (skills, agents, commands)
# Default: all rules disabled, only enable what matters
default: false
# Rules we enforce
MD001: true # Heading levels increment by one
MD003: true # Heading style consistency
MD018: true # No space after hash in heading
MD019: true # Multiple spaces after hash in heading
MD023: true # Headings must start at beginning of line
MD028: true # Blank line inside blockquote
MD037: true # Spaces inside emphasis markers
MD038: true # Spaces inside code span
MD042: true # No empty links
MD046: true # Code block style consistency
MD049: true # Emphasis style consistency
MD050: true # Strong style consistency
